### ISSUE TITLE
OTFS Pilot-Based channel estimation without fractional doppler

### ISSUE THREAD

**Issue by anafreis** [hassiweb/otfs-chan-est-and-eq#6]
Hello!

Thank you for sharing these interesting results and making the codes available.

I would like to know if you have any implementation done for OTFS Pilot-Based channel estimation in a channel that does not consider fractional doppler. 

I started working on DNN-based channel estimation for OTFS with pilot insertion and channel estimation being done in the frequency domain, taking advantage of its properties of OTFS compared to OFDM and without increasing the complexity of going to DD domain estimation.  I think that comparing the estimators I am proposing to your proposal will be a great indicator of the next steps, but I'm facing problems in changing the functions that implement the fading to design a channel without this fractional effect. That is crucial to have identical scenarios for a fair comparison between our estimators.

Again, thank you so much for your valuable work and help.

**Comment by hassiweb** [comment]
Hi @anafreis ,

Thank you for looking at my previous work and asking me.
Since this work was done a few years ago, actually I don't remember completely but you can probably hack the code to generate only integer Doppler by changing the following codes and configured fDoppler in the main code to be integer in the DD domain.  As you can see the Doppler frequency at the receiver is calculated by these codes.

https://github.com/hassiweb/otfs-chan-est-and-eq/blob/6fc82058cacdb87efa754e217546eebf2c0edafc/classes/SoSBasedChannel.m#L125

Thank you.

**Comment by anafreis** [comment]
Hello,

Thank you for your answer. As suggested, I changed the fDoppler calculation in the main code and also made the following adaptation in SoSBasedChannel.m:

From 

`if this.NumRxAntennas == 1  % for K=1, Jakes model (Monte Carlo Method)

    aoa = 2*pi*rand(1,numSinusoids);  % angle of arrival
    this.pathDopplers = this.DopplerFrequency * cos(aoa);

else`

to

`if this.NumRxAntennas == 1  % for K=1, Jakes model (Monte Carlo Method)

    aoa = 2*pi*ones(1,numSinusoids);  % angle of arrival
    this.pathDopplers = this.DopplerFrequency * cos(aoa);

else`

**Comment by hassiweb** [comment]
Hi,

If the suggested change works well and the original issue was resolved, please close this issue.

Thanks.
